/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SearchView_viewer.graphql
 * @generated SignedSource<<e7a0ddb62c0e7d56e1badb98f429353a>>
 * @flow
 * @nogrep
 */

'use strict'

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SearchView_viewer = {
  search?: ?SearchView_viewer_search;
};

export type SearchView_viewer_search_pageInfo = {
  hasNextPage: boolean;
  endCursor?: ?string;
};

export type SearchView_viewer_search_edges_node_owner = {
  avatarUrl: any;
  login: string;
};

export type SearchView_viewer_search_edges_node_stargazers = {
  totalCount: number;
};

export type SearchView_viewer_search_edges_node_watchers = {
  totalCount: number;
};

export type SearchView_viewer_search_edges_node_primaryLanguage = {
  color?: ?string;
  name: string;
};

export type SearchView_viewer_search_edges_node = {
  id?: string;
  name?: string;
  description?: ?string;
  url?: any;
  homepageUrl?: ?any;
  license?: ?string;
  owner?: SearchView_viewer_search_edges_node_owner;
  stargazers?: SearchView_viewer_search_edges_node_stargazers;
  watchers?: SearchView_viewer_search_edges_node_watchers;
  primaryLanguage?: ?SearchView_viewer_search_edges_node_primaryLanguage;
};

export type SearchView_viewer_search_edges = {
  node?: ?SearchView_viewer_search_edges_node;
};

export type SearchView_viewer_search = {
  pageInfo: SearchView_viewer_search_pageInfo;
  edges?: ?Array<?SearchView_viewer_search_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [
    {
      kind: 'RootArgument',
      name: 'count',
      type: 'Int'
    },
    {
      kind: 'RootArgument',
      name: 'cursor',
      type: 'String'
    },
    {
      kind: 'RootArgument',
      name: 'query',
      type: 'String!'
    }
  ],
  kind: 'Fragment',
  metadata: {
    connection: [
      {
        count: 'count',
        cursor: 'cursor',
        direction: 'forward',
        path: ['search']
      }
    ]
  },
  name: 'SearchView_viewer',
  selections: [
    {
      kind: 'LinkedField',
      alias: 'search',
      args: [
        {
          kind: 'Variable',
          name: 'query',
          variableName: 'query',
          type: 'String!'
        },
        {
          kind: 'Literal',
          name: 'type',
          value: 'REPOSITORY',
          type: 'SearchType!'
        }
      ],
      concreteType: 'SearchResultItemConnection',
      name: '__SearchView_search_connection',
      plural: false,
      selections: [
        {
          kind: 'LinkedField',
          alias: null,
          args: null,
          concreteType: 'PageInfo',
          name: 'pageInfo',
          plural: false,
          selections: [
            {
              kind: 'ScalarField',
              alias: null,
              args: null,
              name: 'hasNextPage',
              storageKey: null
            },
            {
              kind: 'ScalarField',
              alias: null,
              args: null,
              name: 'endCursor',
              storageKey: null
            }
          ],
          storageKey: null
        },
        {
          kind: 'LinkedField',
          alias: null,
          args: null,
          concreteType: 'SearchResultItemEdge',
          name: 'edges',
          plural: true,
          selections: [
            {
              kind: 'LinkedField',
              alias: null,
              args: null,
              concreteType: null,
              name: 'node',
              plural: false,
              selections: [
                {
                  kind: 'InlineFragment',
                  type: 'Repository',
                  selections: [
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'id',
                      storageKey: null
                    },
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'name',
                      storageKey: null
                    },
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'description',
                      storageKey: null
                    },
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'url',
                      storageKey: null
                    },
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'homepageUrl',
                      storageKey: null
                    },
                    {
                      kind: 'ScalarField',
                      alias: null,
                      args: null,
                      name: 'license',
                      storageKey: null
                    },
                    {
                      kind: 'LinkedField',
                      alias: null,
                      args: null,
                      concreteType: null,
                      name: 'owner',
                      plural: false,
                      selections: [
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'avatarUrl',
                          storageKey: null
                        },
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'login',
                          storageKey: null
                        }
                      ],
                      storageKey: null
                    },
                    {
                      kind: 'LinkedField',
                      alias: null,
                      args: null,
                      concreteType: 'StargazerConnection',
                      name: 'stargazers',
                      plural: false,
                      selections: [
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'totalCount',
                          storageKey: null
                        }
                      ],
                      storageKey: null
                    },
                    {
                      kind: 'LinkedField',
                      alias: null,
                      args: null,
                      concreteType: 'UserConnection',
                      name: 'watchers',
                      plural: false,
                      selections: [
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'totalCount',
                          storageKey: null
                        }
                      ],
                      storageKey: null
                    },
                    {
                      kind: 'LinkedField',
                      alias: null,
                      args: null,
                      concreteType: 'Language',
                      name: 'primaryLanguage',
                      plural: false,
                      selections: [
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'color',
                          storageKey: null
                        },
                        {
                          kind: 'ScalarField',
                          alias: null,
                          args: null,
                          name: 'name',
                          storageKey: null
                        }
                      ],
                      storageKey: null
                    }
                  ]
                }
              ],
              storageKey: null
            }
          ],
          storageKey: null
        }
      ],
      storageKey: null
    }
  ],
  type: 'Query'
}

module.exports = fragment
